notifications:
  email:
    recipients:
      - jims.astronomy@gmail.com
    on_success: change
    on_failure: change


dist: xenial
language: python

jobs:
  include:
      - python: 3.6
      - python: 3.7
      - python: 3.7-dev
      - python: 3.8
      - python: 3.8-dev
      - python: 3.9-dev
    allow_failures:
      - python: 3.7-dev
      - python: 3.8-dev
      - python: 3.9-dev
    fast_finish: true


before_install:
  - python --version
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - python setup.py install
  - pip install pytest pytest-cov
  - pip install codecov

install:
  - python setup.py sdist bdist_wheel

script:
  - pytest --cov

after_success:
  - codecov
