dist: xenial
language: python

notifications:
  email:
    recipients:
      - jims.astronomy@gmail.com
    on_success: change
    on_failure: always

matrix:

  # linux
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8
    - python: 3.8-dev
    - python: 3.9-dev
  allow_failures:
    - python: 3.7-dev
    - python: 3.8-dev
    - python: 3.9-dev

    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install:
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - python setup.py install
  - pip install pytest pytest-cov
  - pip install codecov

install:
  - python setup.py sdist bdist_wheel

script:
  - pytest --cov

after_success:
  - codecov








# https://github.com/codecov/codecov-bash/issues/94 codecov errors re: bash
# https://github.com/codecov/example-python
