dist: xenial
language: python

python:
  - 3.6
  - 3.7
  - 3.7-dev
  - 3.8
  - 3.8-dev
  - 3.9-dev

jobs:
  include:
    - name: "Python 3.7.5 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.5, macOS 10.14.3
      language: shell
      before_install:
        - python3 --version
        - pip3 install --upgrade pip setuptools wheel
        - pip3 install -r requirements.txt
        - pip3 install --upgrade pytest pytest-cov
        - pip3 install codecov
      script: python3 -m pytest
      after_success: python 3 -m codecov

    - name: "Python 3.7.4 on Windows"
      os: windows     # Windows 10.0.17134 N/A Build 17134
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip setuptools wheel
        - pip3 install -r requirements.txt
        - pip3 install --upgrade pytest pytest-cov
        - pip3 install codecov
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

  allow_failures:
    - python: 3.7-dev
    - python: 3.8-dev
    - python: 3.9-dev
    - os: windows
    - os: osx
  fast_finish: true


before_install:
  - python --version
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - python setup.py install
  - pip install pytest pytest-cov
  - pip install codecov

install:
  - python setup.py sdist bdist_wheel

script:
  - pytest --cov

after_success:
  - codecov


notifications:
  email:
    recipients:
      - jims.astronomy@gmail.com
    on_success: change
    on_failure: change
